//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessBLL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SexSpider
    {
        public int SiteId { get; set; }
        public string SiteRank { get; set; }
        public byte VipLevel { get; set; }
        public byte IsHided { get; set; }
        public string SiteName { get; set; }
        public string ListPage { get; set; }
        public string PageEncode { get; set; }
        public string Domain { get; set; }
        public string SiteLink { get; set; }
        public string ListDiv { get; set; }
        public string ImageDiv { get; set; }
        public string PageDiv { get; set; }
        public byte PageLevel { get; set; }
        public string ListFilter { get; set; }
        public string ImageFilter { get; set; }
        public string PageFilter { get; set; }
        public string DocType { get; set; }
        public string SiteFilter { get; set; }
    }
}
